/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CikkekSelfCheckAiRouteImport } from './routes/cikkek/self-check-ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CikkekSelfCheckAiRoute = CikkekSelfCheckAiRouteImport.update({
  id: '/cikkek/self-check-ai',
  path: '/cikkek/self-check-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cikkek/self-check-ai': typeof CikkekSelfCheckAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cikkek/self-check-ai': typeof CikkekSelfCheckAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cikkek/self-check-ai': typeof CikkekSelfCheckAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cikkek/self-check-ai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cikkek/self-check-ai'
  id: '__root__' | '/' | '/cikkek/self-check-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CikkekSelfCheckAiRoute: typeof CikkekSelfCheckAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cikkek/self-check-ai': {
      id: '/cikkek/self-check-ai'
      path: '/cikkek/self-check-ai'
      fullPath: '/cikkek/self-check-ai'
      preLoaderRoute: typeof CikkekSelfCheckAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CikkekSelfCheckAiRoute: CikkekSelfCheckAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
