/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PenzugyiOnvedelemRouteImport } from './routes/penzugyi-onvedelem'
import { Route as EncodingTestRouteImport } from './routes/encoding-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as CikkekIndexRouteImport } from './routes/cikkek/index'
import { Route as CikkekSlugRouteImport } from './routes/cikkek/$slug'
import { Route as EnArticlesIndexRouteImport } from './routes/en/articles/index'
import { Route as EnArticlesSlugRouteImport } from './routes/en/articles/$slug'

const PenzugyiOnvedelemRoute = PenzugyiOnvedelemRouteImport.update({
  id: '/penzugyi-onvedelem',
  path: '/penzugyi-onvedelem',
  getParentRoute: () => rootRouteImport,
} as any)
const EncodingTestRoute = EncodingTestRouteImport.update({
  id: '/encoding-test',
  path: '/encoding-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const CikkekIndexRoute = CikkekIndexRouteImport.update({
  id: '/cikkek/',
  path: '/cikkek/',
  getParentRoute: () => rootRouteImport,
} as any)
const CikkekSlugRoute = CikkekSlugRouteImport.update({
  id: '/cikkek/$slug',
  path: '/cikkek/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArticlesIndexRoute = EnArticlesIndexRouteImport.update({
  id: '/en/articles/',
  path: '/en/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArticlesSlugRoute = EnArticlesSlugRouteImport.update({
  id: '/en/articles/$slug',
  path: '/en/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/encoding-test': typeof EncodingTestRoute
  '/penzugyi-onvedelem': typeof PenzugyiOnvedelemRoute
  '/cikkek/$slug': typeof CikkekSlugRoute
  '/cikkek/': typeof CikkekIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/articles/': typeof EnArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/encoding-test': typeof EncodingTestRoute
  '/penzugyi-onvedelem': typeof PenzugyiOnvedelemRoute
  '/cikkek/$slug': typeof CikkekSlugRoute
  '/cikkek': typeof CikkekIndexRoute
  '/en': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/articles': typeof EnArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/encoding-test': typeof EncodingTestRoute
  '/penzugyi-onvedelem': typeof PenzugyiOnvedelemRoute
  '/cikkek/$slug': typeof CikkekSlugRoute
  '/cikkek/': typeof CikkekIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/articles/': typeof EnArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/encoding-test'
    | '/penzugyi-onvedelem'
    | '/cikkek/$slug'
    | '/cikkek/'
    | '/en/'
    | '/en/articles/$slug'
    | '/en/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/encoding-test'
    | '/penzugyi-onvedelem'
    | '/cikkek/$slug'
    | '/cikkek'
    | '/en'
    | '/en/articles/$slug'
    | '/en/articles'
  id:
    | '__root__'
    | '/'
    | '/encoding-test'
    | '/penzugyi-onvedelem'
    | '/cikkek/$slug'
    | '/cikkek/'
    | '/en/'
    | '/en/articles/$slug'
    | '/en/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EncodingTestRoute: typeof EncodingTestRoute
  PenzugyiOnvedelemRoute: typeof PenzugyiOnvedelemRoute
  CikkekSlugRoute: typeof CikkekSlugRoute
  CikkekIndexRoute: typeof CikkekIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  EnArticlesSlugRoute: typeof EnArticlesSlugRoute
  EnArticlesIndexRoute: typeof EnArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/penzugyi-onvedelem': {
      id: '/penzugyi-onvedelem'
      path: '/penzugyi-onvedelem'
      fullPath: '/penzugyi-onvedelem'
      preLoaderRoute: typeof PenzugyiOnvedelemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encoding-test': {
      id: '/encoding-test'
      path: '/encoding-test'
      fullPath: '/encoding-test'
      preLoaderRoute: typeof EncodingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cikkek/': {
      id: '/cikkek/'
      path: '/cikkek'
      fullPath: '/cikkek/'
      preLoaderRoute: typeof CikkekIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cikkek/$slug': {
      id: '/cikkek/$slug'
      path: '/cikkek/$slug'
      fullPath: '/cikkek/$slug'
      preLoaderRoute: typeof CikkekSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/articles/': {
      id: '/en/articles/'
      path: '/en/articles'
      fullPath: '/en/articles/'
      preLoaderRoute: typeof EnArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/articles/$slug': {
      id: '/en/articles/$slug'
      path: '/en/articles/$slug'
      fullPath: '/en/articles/$slug'
      preLoaderRoute: typeof EnArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EncodingTestRoute: EncodingTestRoute,
  PenzugyiOnvedelemRoute: PenzugyiOnvedelemRoute,
  CikkekSlugRoute: CikkekSlugRoute,
  CikkekIndexRoute: CikkekIndexRoute,
  EnIndexRoute: EnIndexRoute,
  EnArticlesSlugRoute: EnArticlesSlugRoute,
  EnArticlesIndexRoute: EnArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
